#!/bin/bash -x
# Sandboxing. Temporary files

FMT="+%Y-%m-%d"
DATE=$(date $FMT)
NOTEDIR=$HOME/.tdoc

function dmkdir()
{
    prefix=$1
    date=$2
    year=$(date --date="$date" "+%Y")
    month=$(date --date="$date" "+%m")
    day=$(date --date="$date" "+%d")
    DIR=$prefix/$year/$month/$day
}

# Get the directory for a specific date. Tries to understand modifiers like
# "yesterday"
function getdir()
{
    prefix="$HOME/temp"
    dmkdir $prefix $1
}

function td()
{
    # Fallback
    DIR="$HOME/temp/"
    getdir "$@"
    if [ ! -e $DIR ]
    then
        mkdir -p $DIR
    fi
    cd $DIR
}

function tdoc()
{
    file="$NOTEDIR/daily-$DATE.txt"
    if [ ! -e $NOTEDIR ]
    then
	mkdir -p $NOTEDIR
    fi
    vim -c "set filetype=help" $file
    vim -e -c "helptags $NOTEDIR" -c q
}

function notes()
{
    filename=""
    case $1 in
	*.txt) filename=$1;;
	*) filename="$1".txt;;
    esac
    file="$NOTEDIR/$filename"
    if [ ! -e $NOTEDIR ]
    then
	mkdir -p $NOTEDIR
    fi
    echo $file
    vim $file
    vim -e -c "helptags $NOTEDIR" -c q
}

#export -f td
#export -f getdir
